### ISSUE TITLE
atualizar badge de CI no README para CircleCI

### ISSUE THREAD

**Issue by adrianomitre** [Xerpa/bank_validator_br#10]
Deveria ter sido feito no [PR que migrou pro CircleCI](https://github.com/Xerpa/bank_validator_br/pull/8), mas infelizmente passou batido.

Referência:
* [Adding Status Badges - CircleCI](https://circleci.com/docs/2.0/status-badges/)

**Comment by adrianomitre** [comment]
https://github.com/Xerpa/bank_validator_br/commit/54c57528afa893e86d73256743156fda899cdc15#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by adrianomitre** [comment]
Sugestão para manter os vínculos/rastreabilidade: "By prefacing your commits with “Fixes”, “Fixed”, “Fix”, “Closes”, “Closed”, or “Close” when the commit is merged into main, it will also automatically close the issue."
Fonte: https://guides.github.com/features/issues/

**Comment by itsmegrave** [comment]
eu acabei usando os super poderes no lugar de fazer o PR...
Vou evitar fazer isso, mesmo em mudanças pequenas como essa no readme :)
