### ISSUE TITLE
Validação do digito incorreta

### ISSUE THREAD

**Issue by itsmegrave** [Xerpa/bank_validator_br#6]
A validação abaixo precisa ser quebrada.
A regra diz que se o `digit_result` for 10, ele deve ter o valor `0`.
Então a variavel `digit_result` precisa ser modificada e ai fazer a comparação se `digit_result == digit`

https://github.com/Xerpa/bank_validator_br/blob/7d4bfe775d10bb5e26343aaab420984a5d7b25f1/lib/banks/itau.ex#L25

**Comment by adrianomitre** [comment]
Não seria o caso de usar aritmética modular, pegando o resto da divisão por 10 com `rem(n, 10)`?
